name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ Do not open issues for Windows executables not working in Bottles, if not installed through our installers. Bottles is a Wine prefix manager. If a Windows application doesn't work, it could be a Wine problem or a misconfiguration of the Wine prefix. Please visit [WineHQ](https://www.winehq.org) and [ProtonDB](https://www.protondb.com) for more information on the software you are trying to run. For additional support, use the [Programs](https://github.com/bottlesdevs/programs) repository.
        ⚠️ Do not open issues for Windows executables not working in Bottles, if not installed through our installers. Bottles is a Wine prefix manager. If a Windows application doesn't work, it could be a Wine problem or a misconfiguration of the Wine prefix. Please visit [WineHQ](https://www.winehq.org) and [ProtonDB](https://www.protondb.com) for more information on the software you are trying to run.
        ⚠️ Do not open issues for bugs regarding the Flatpak version here. This is a specialized native (Deflatpak) fork.

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: Also tell us, what did you expect to happen?
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## System information

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: |
        How did you install Bottles?
      options:
        - AUR (Arch Linux)
        - RPM (Fedora/RHEL)
        - DEB (Debian/Ubuntu)
        - Binary Tarball (.tar.gz)
        - Compiled from source
    validations:
      required: true

  - type: input
    id: distro
    attributes:
      label: Distribution
      description: In which Linux distribution did you encounter the bug?
      placeholder: Fedora 41, Arch Linux, Ubuntu 24.04..
    validations:
      required: true

  - type: textarea
    id: health-check
    attributes:
      label: Debugging Information
      description: |
        In Bottles, press the hamburger menu (`☰`) at the top right. Then press "About Bottles". Select "Troubleshooting", then "Debugging Information". Lastly, copy text and paste here.

        If you are unable to run Bottles, then you can retrieve information by running `bottles-cli info health-check` in the terminal.
      render: shell
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: Troubleshooting Logs
      description: If applicable, run `bottles`, reproduce the issue and paste the logs here.
      render: shell
      placeholder: |
        [Errno 2] No such file or directory: '/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles/Opera-GX__185/bottle.yml'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 61, in __target
            result = self.task_func(*args, **kwargs)

          File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 194, in get_manager
            mng = Manager(window=window, repo_fn_update=repo_fn_update)

          File "/app/share/bottles/bottles/backend/managers/manager.py", line 135, in __init__
            times.update(self.checks(install_latest=False, first_run=True).data)

          File "/app/share/bottles/bottles/backend/managers/manager.py", line 189, in checks
            self.check_bottles()

          File "/app/share/bottles/bottles/backend/managers/manager.py", line 804, in check_bottles
            process_bottle(b)

          File "/app/share/bottles/bottles/backend/managers/manager.py", line 758, in process_bottle
            self.update_config(

          File "/app/share/bottles/bottles/backend/managers/manager.py", line 874, in update_config
            with open(os.path.join(bottle_path, "bottle.yml"), "w") as conf_file

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
